server:
  port: 9000
  error:
    include-binding-errors: always
    include-message: always
    include-stacktrace: never
spring:
  application:
    name: cards
  profiles:
    active: "prod"
  config:
    import: "optional:configserver:http://localhost:8082/"
  datasource:
    url: jdbc:postgresql://localhost:5432/cards_db
    username: postgres
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    deserialization:
      fail-on-unknown-properties: true
  cloud:
    function:
      definition: updateCardMobileNumber;rollbackCardMobileNumber
    stream:
      bindings:
        updateCardMobileNumber-in-0:
          destination: update-card-mobile-number
          group: ${spring.application.name}
        rollbackCardMobileNumber-in-0:
          destination: rollback-card-mobile-number
          group: ${spring.application.name}
        updateLoanMobileNumber-out-0:
          destination: update-loan-mobile-number
        rollbackAccountMobileNumber-out-0:
          destination: rollback-account-mobile-number
      kafka:
        binder:
          brokers:
            - localhost:9092
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/
    fetch-registry: true
    register-with-eureka: true