server:
  port: 9000
  error:
    include-binding-errors: always
    include-message: always
    include-stacktrace: never
spring:
  application:
    name: cards
  datasource:
    url: jdbc:postgresql://cards_pgcn:5433/cards_db
    username: postgres
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    deserialization:
      fail-on-unknown-properties: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://service-registry-ms:8081/eureka/
    fetch-registry: true
    register-with-eureka: true