server:
  port: 8081
spring:
  application:
    name: service-registry
eureka:
  client:
    serviceUrl:
      defaultZone: http://service-registry-ms:8081/eureka/
    fetch-registry: false
    register-with-eureka: false