server:
  port: 8080
spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://config-server-ms:8082/"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: accouts
          uri: http://accounts-ms:9002
          predicates:
            - Path=/api/accounts/**
        - id: loans
          uri: http://loans-ms:9001
          predicates:
            - Path=/api/loans/**
        - id: cards
          uri: http://cards-ms:9000
          predicates:
            - Path=/api/cards/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://service-registry-ms:8081/eureka/
    fetch-registry: true
    register-with-eureka: true