build:
  version: "2.0"

accounts:
  message: "Welcome to Ali Bank, ACCOUNTS-QA Service Support Info"
  contactDetails:
    name: "Md Ali - Developer(QA)"
    email: "md.ali@icress-qa.com"
  onCallSupport:
    - (111) 111-1234
    - (222) 222-1234