build:
  version: "2.0"

accounts:
  message: "Welcome to Ali Bank, ACCOUNTS Service Support Info"
  contactDetails:
    name: "Md Ali - Developer"
    email: "md.ali@icress.com"
  onCallSupport:
    - (111) 111-1234
    - (222) 222-1234