build:
  version: "1.0"

cards:
  message: "Welcome to Ali Bank, CARDS-LOCAL Service Support Info"
  contactDetails:
    name: "Md Ali - Developer(LOCAL)"
    email: "md.ali@icress-local.com"
  onCallSupport:
    - (333) 333-123456
    - (444) 444-123456