build:
  version: "1.0"

cards:
  message: "Welcome to Ali Bank, CARDS-QA Service Support Info"
  contactDetails:
    name: "Md Ali - Developer(QA)"
    email: "md.ali@icress-qa.com"
  onCallSupport:
    - (333) 333-123456
    - (444) 444-123456