build:
  version: "1.0"

loans:
  message: "Welcome to Ali Bank, LOANS-QA Service Support Info"
  contactDetails:
    name: "Md Ali - Developer(QA)"
    email: "md.ali@icress-qa.com"
  onCallSupport:
    - (555) 555-123456
    - (666) 666-123456