build:
  version: "1.0"

loans:
  message: "Welcome to Ali Bank, LOANS-DEV Service Support Info"
  contactDetails:
    name: "Md Ali - Developer(DEV)"
    email: "md.ali@icress-dev.com"
  onCallSupport:
    - (555) 555-123456
    - (666) 666-123456